services:

  # MySQL Service
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: katze
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - vol_mysql:/var/lib/mysql
    networks:
      - app-network

  # Redis Service
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - vol_redis:/data
    networks:
      - app-network

  # MeiliSearch Service
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    restart: unless-stopped
    ports:
      - "7700:7700"
    volumes:
      - vol_meilisearch:/data.ms
    networks:
      - app-network

  # MailCatcher Service
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    tty: true
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web Interface
    networks:
      - app-network

  # WebSocket Service
  websocket:
    image: quay.io/soketi/soketi:latest
    container_name: websocket
    restart: unless-stopped
    tty: true
    ports:
      - "6001:6001"
      - "9601:9601"
    environment:
      SOKETI_DEBUG: '0'
      SOKETI_METRICS_SERVER_PORT: '9601'
      SOKETI_DEFAULT_APP_ID: 'your-pusher-app-id'
      SOKETI_DEFAULT_APP_KEY: 'your-pusher-key'
      SOKETI_DEFAULT_APP_SECRET: 'your-pusher-secret'
    networks:
      - app-network

volumes:
  vol_mysql:
    driver: local
  vol_redis:
    driver: local
  vol_meilisearch:
    driver: local

networks:
  app-network:
    driver: bridge