services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APP_PORT=8000
            - DB_HOST=mysql
            - DB_DATABASE=your_db
            - DB_USERNAME=your_user
            - DB_PASSWORD=your_password
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
