services:

  # Katze Backend Service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: katze-backend
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
      - meilisearch
      - mailcatcher
    tty: true
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: katze
      DB_USERNAME: root
      DB_PASSWORD: root
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_STORE: redis
      SESSION_DRIVER: redis
      MAIL_MAILER: smtp
      MAIL_HOST: mailcatcher
      MAIL_PORT: 1025
      MEILISEARCH_HOST: http://katze-meilisearch:7700
      MEILISEARCH_KEY: katze-meilisearch

    working_dir: /var/www/laravel
    volumes:
      - ./laravel/app:/var/www/laravel/app
      - ./laravel/routes:/var/www/laravel/routes
      - ./laravel/database:/var/www/laravel/database
      - ./laravel/resources:/var/www/laravel/resources
      - ./laravel/config:/var/www/laravel/config
      - ./laravel/storage:/var/www/laravel/storage
      - ./laravel/tests:/var/www/laravel/tests
      - ./laravel/lang:/var/www/laravel/lang
    networks:
      - app-network
    ports:
      - "22:22"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    environment:
      API_URL: http://localhost:80/openapi.yaml
    ports:
      - "8001:8080"
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - app

  # Nginx Service
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/development/conf.d:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - app-network

  # MySQL Service
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: katze
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app-network

  # Redis Service
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    networks:
      - app-network

  # MeiliSearch Service
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    restart: unless-stopped
    ports:
      - "7700:7700"
    volumes:
      - ./data.ms:/data.ms
    networks:
      - app-network

  # MailCatcher Service
  mailcatcher:
    image: schickling/mailcatcher:latest
    container_name: mailcatcher
    restart: unless-stopped
    tty: true
    ports:
      - "1025:1025" # SMTP
      - "1080:1080" # Web Interface
    networks:
      - app-network

  # WebSocket Service
  websocket:
    image: quay.io/soketi/soketi:latest
    container_name: websocket
    restart: unless-stopped
    tty: true
    ports:
      - "6001:6001"
      - "9601:9601"
    networks:
      - app-network
volumes:
  mysql:

networks:
  app-network:
    driver: bridge