services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APP_PORT=8000
            - DB_HOST=mysql
            - DB_DATABASE=your_db
            - DB_USERNAME=your_user
            - DB_PASSWORD=your_password
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: your_db
            MYSQL_USER: your_user
            MYSQL_PASSWORD: your_password
            MYSQL_ROOT_PASSWORD: root_password
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    mysql-data:
