apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: katze-backend
  labels:
    app: katze-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: katze-backend
  template:
    metadata:
      labels:
        app: katze-backend
    spec:
      securityContext:
        fsGroup: 82
      initContainers:
        - name: init-storage-permission
          image: busybox
          command: ['sh', '-c', 'chmod -R 777 /var/www/laravel/storage && chown -R 82:82 /var/www/laravel/storage']
          volumeMounts:
            - name: app-pvc
              mountPath: /var/www/laravel/storage
          securityContext:
            runAsUser: 0
      containers:
        - name: katze-backend
          image: ghcr.io/martinkribs/katze-backend:main
          imagePullPolicy: Always
          workingDir: /var/www/laravel
          ports:
            - containerPort: 9000
              name: fpm
          securityContext:
            runAsUser: 82
            runAsGroup: 82
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: APP_ENV
              value: "production"
            - name: APP_DEBUG
              value: "false"
            - name: APP_URL
              value: "https://katze.app"
            - name: DB_HOST
              value: "mysql"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_PASSWORD
            - name: RESEND_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RESEND_KEY
            - name: MAIL_MAILER
              value: "resend"
            - name: MEILISEARCH_HOST
              value: "http://meilisearch:7700"
            - name: MEILISEARCH_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MEILISEARCH_KEY
            - name: PUSHER_APP_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SOKETI_DEFAULT_APP_ID
            - name: PUSHER_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SOKETI_DEFAULT_APP_KEY
            - name: PUSHER_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SOKETI_DEFAULT_APP_SECRET
            - name: PUSHER_HOST
              value: "soketi.katze.app"
            - name: PUSHER_PORT
              value: "443"
            - name: PUSHER_SCHEME
              value: "https"
          volumeMounts:
            - name: app-pvc
              mountPath: /var/www/laravel/storage
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 20
      imagePullSecrets:
        - name: docker-secrets
      volumes:
        - name: app-pvc
          persistentVolumeClaim:
            claimName: app-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: katze-backend
  namespace: katze-backend
spec:
  selector:
    app: katze-backend
  ports:
    - protocol: TCP
      name: fpm
      port: 9000
      targetPort: 9000
