apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: katze-backend
  labels:
    app: katze-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: katze-backend
  template:
    metadata:
      labels:
        app: katze-backend
    spec:
      containers:
        - name: katze-backend
          image: ghcr.io/martinkribs/katze-backend:main
          imagePullPolicy: Always
          workingDir: /var/www/laravel
          ports:
            - containerPort: 9000
              name: fpm
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: APP_ENV
              value: "production"
            - name: APP_DEBUG
              value: "false"
            - name: APP_URL
              value: "https://katze.app"
            - name: DB_HOST
              value: "mysql"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_PASSWORD
            - name: MAIL_HOST
              value: "mailu.katze.app"
            - name: MAIL_PORT
              value: "587"
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MAIL_PASSWORD
            - name: MAIL_ENCRYPTION
              value: "tls"
            - name: MEILISEARCH_HOST
              value: "http://meilisearch:7700"
            - name: MEILISEARCH_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MEILISEARCH_KEY
            - name: PUSHER_APP_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SOKETI_DEFAULT_APP_ID
            - name: PUSHER_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SOKETI_DEFAULT_APP_KEY
            - name: PUSHER_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SOKETI_DEFAULT_APP_SECRET
          volumeMounts:
            - name: app-pvc
              mountPath: /katze
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "cp -r /var/www/laravel/. /katze" ]
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 20
      imagePullSecrets:
        - name: docker-secrets
      volumes:
        - name: app-pvc
          persistentVolumeClaim:
            claimName: app-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: katze-backend
  namespace: katze-backend
spec:
  selector:
    app: katze-backend
  ports:
    - protocol: TCP
      name: fpm
      port: 9000
      targetPort: 9000
