apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: katze-backend

spec:
  rules:
    - host: "katze.app"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
    - host: "swagger.katze.app"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swagger-ui
                port:
                  number: 8001
    - host: "mailcatcher.katze.app"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mailcatcher
                port:
                  number: 1080
    - host: "meilisearch.katze.app"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meilisearch
                port:
                  number: 7700