apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: katze-backend
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - katze.app
        - soketi.katze.app
  rules:
    - host: "katze.app"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
    - host: "soketi.katze.app"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: soketi
                port:
                  number: 6001
