apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailu
  namespace: katze-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailu
  template:
    metadata:
      labels:
        app: mailu
    spec:
      containers:
        - name: mailu
          image: mailu/main:latest
          ports:
            - containerPort: 443  # HTTPS
            - containerPort: 25   # SMTP
            - containerPort: 465  # SMTPS
            - containerPort: 587  # Submission
            - containerPort: 143  # IMAP
            - containerPort: 993  # IMAPS
          env:
            - name: DOMAIN
              value: katze.app
            - name: HOSTNAMES
              value: mail.katze.app
            - name: TLS_FLAVOR
              value: cert
            - name: POSTMASTER
              valueFrom:
                secretKeyRef:
                  name: mailu-secrets
                  key: postmaster
            - name: INITIAL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailu-secrets
                  key: admin-password
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mailu-secrets
                  key: secret-key
          volumeMounts:
            - name: mailu-data
              mountPath: /mailu
            - name: mailu-certs
              mountPath: /certs
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
      volumes:
        - name: mailu-data
          persistentVolumeClaim:
            claimName: mailu-pvc
        - name: mailu-certs
          persistentVolumeClaim:
            claimName: mailu-certs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mailu
  namespace: katze-backend
spec:
  selector:
    app: mailu
  ports:
    - name: https
      port: 443
      protocol: TCP
    - name: smtp
      port: 25
      protocol: TCP
    - name: imap
      port: 143
      protocol: TCP
    - name: smtps
      port: 465
      protocol: TCP
    - name: submission
      port: 587
      protocol: TCP
    - name: imaps
      port: 993
      protocol: TCP
