global:
  database:
    roundcube:
      existingSecret: "mailu-secrets"
      existingSecretPasswordKey: "roundcube-password"
hostnames: 
  - mail.katze.app
  - autoconfig.katze.app
  - autodiscover.katze.app
domain: "katze.app"
existingSecret: "mailu-secrets"
timezone: "Europe/Berlin"
initialAccount:
  enabled: true
  username: "mailadmin"
  domain: "katze.app"
  existingSecret: "mailu-secrets"
  existingSecretPasswordKey: "admin-password"
networkPolicy:
  enabled: true
dmarc:
  rua: "failure"
  ruf: "report"
customization:
  siteName: "Katze Mail"
  website: "https://katze.app"
ingress:
  enabled: false
postgresql:
  enabled: true
  auth:
    existingSecret: "mailu-secrets"
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
      replicationPasswordKey: replication-password
  primary:
    persistence:
      enabled: true
