apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailu-pvc
  namespace: katze-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailu-certs-pvc
  namespace: katze-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
