apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: katze-backend
data:
  default.conf: |
    upstream php-fpm {
      server katze-backend:9000;
      keepalive 32;
    }

    server {
      listen 80;
      server_name katze.app open.katze.app;
    
      root /var/www/laravel/public;
      index index.php;

      # Security headers
      add_header X-Frame-Options "SAMEORIGIN";
      add_header X-XSS-Protection "1; mode=block";
      add_header X-Content-Type-Options "nosniff";
      
      # Handle favicon.ico
      location = /favicon.ico {
        access_log off;
        log_not_found off;
      }
      
      location / {
        try_files $uri $uri/ /index.php?$query_string;
      }

      # Handle game-invite route for deep linking
      location /game-invite {
        rewrite ^/game-invite(.*)$ /index.php?$query_string last;
      }
      
      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass php-fpm;
          fastcgi_index index.php;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
          fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;
          
          # Increased buffer sizes
          fastcgi_buffers 16 32k;
          fastcgi_buffer_size 64k;
          
          # Increased timeouts
          fastcgi_read_timeout 600;
          fastcgi_send_timeout 600;
          fastcgi_connect_timeout 60;
          
          # Keep alive settings
          fastcgi_keep_conn on;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
      }

      location ~ /\.(?!well-known).* {
          deny all;
      }

      error_log  /var/log/nginx/error.log warn;
      access_log /var/log/nginx/access.log combined buffer=512k flush=1m;
    }
