# This is a template file. Copy to secrets.yml and fill in your values
# DO NOT commit secrets.yml to git!
# Use base64 encoded values: echo -n "your-value" | base64
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: katze-backend
type: Opaque
data:
  DB_USERNAME: <base64-encoded-value>
  DB_PASSWORD: <base64-encoded-value>
  REDIS_PASSWORD: <base64-encoded-value>
  RESEND_API_KEY: <base64-encoded-value>
  MEILISEARCH_KEY: <base64-encoded-value>
  SOKETI_DEFAULT_APP_ID: <base64-encoded-value>
  SOKETI_DEFAULT_APP_KEY: <base64-encoded-value>
  SOKETI_DEFAULT_APP_SECRET: <base64-encoded-value>

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: katze-backend
type: Opaque
data:
  mysql-root-password: <base64-encoded-value>

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-secrets
  namespace: katze-backend
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-value>
