apiVersion: apps/v1
kind: Deployment
metadata:
  name: soketi
  namespace: katze-backend
  labels:
    app: soketi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soketi
  template:
    metadata:
      labels:
        app: soketi
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: soketi
          image: quay.io/soketi/soketi:1.4-16-debian
          ports:
            - containerPort: 6001
              name: websocket
            - containerPort: 9601
              name: websocket-2
          env:
            - name: SOKETI_DEBUG
              value: "1"
            - name: SOKETI_DEFAULT_APP_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SOKETI_DEFAULT_APP_ID
            - name: SOKETI_DEFAULT_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SOKETI_DEFAULT_APP_KEY
            - name: SOKETI_DEFAULT_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SOKETI_DEFAULT_APP_SECRET
          resources:
            limits:
              memory: "256Mi"
              cpu: "300m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /ready
              port: 6001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 6001
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: soketi
  namespace: katze-backend
spec:
  selector:
    app: soketi
  ports:
    - protocol: TCP
      port: 6001
      name: websocket
      targetPort: 6001
    - protocol: TCP
      port: 9601
      name: websocket-2
      targetPort: 9601
