apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
  namespace: iso-backend
  labels:
    app: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
        - name: swagger-ui
          image: swaggerapi/swagger-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: API_URL
              value: "http://katze.app/openapi.yaml"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-ui
  namespace: katze-backend
spec:
  selector:
    app: swagger-ui
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8080