apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    persistence:
      enabled: true
      existingClaim: traefik-certificates
    ingressRoute:
      dashboard:
        enabled: false
    providers:
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        publishedService:
          enabled: true
        allowCrossNamespace: true
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          certResolver: le
    entryPoints:
      websecure:
        address: ":443"
        http:
          tls:
            certResolver: le
    additionalArguments:
      - --certificatesresolvers.le.acme.email=martin.kribs.mk@gmail.com
      - --certificatesresolvers.le.acme.storage=/data/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
