apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
  - --certificatesresolvers.le-staging.acme.email=martin.kribs.mk@gmail.com
  - --certificatesresolvers.le-staging.acme.storage=/data/acme-staging.json
  - --certificatesresolvers.le-staging.acme.tlschallenge=true
  - --certificatesresolvers.le-staging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory