name: Build & Push Frontend Docker Image
on:
  push:
    branches: [ main ]
    paths:
      - 'download-page/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'download-page'
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout GitHub Action' 
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build & push image'
        run: |
          docker build -f Dockerfile --tag ghcr.io/martinkribs/katze-frontend:${GITHUB_REF##*/} .
          docker push ghcr.io/martinkribs/katze-frontend:${GITHUB_REF##*/}
