name: Build & Push Docker Image for Production
on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '.'
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout GitHub Action' 
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build & push image'
        run: |
          chmod +x ./docker/startup_script.sh
          docker build -f docker/Dockerfile --tag ghcr.io/martinkribs/katze-backend:${GITHUB_REF##*/} .
          docker push ghcr.io/martinkribs/katze-backend:${GITHUB_REF##*/}
